#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20201013_DatabaseUzduotis
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ZmogausOrganai")]
	public partial class ZmogausOrganaiConverterDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertZmogus(Zmogus instance);
    partial void UpdateZmogus(Zmogus instance);
    partial void DeleteZmogus(Zmogus instance);
    partial void InsertOrganai(Organai instance);
    partial void UpdateOrganai(Organai instance);
    partial void DeleteOrganai(Organai instance);
    #endregion
		
		public ZmogausOrganaiConverterDataContext() : 
				base(global::_20201013_DatabaseUzduotis.Properties.Settings.Default.ZmogausOrganaiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ZmogausOrganaiConverterDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZmogausOrganaiConverterDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZmogausOrganaiConverterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZmogausOrganaiConverterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Zmogus> Zmogus
		{
			get
			{
				return this.GetTable<Zmogus>();
			}
		}
		
		public System.Data.Linq.Table<Organai> Organais
		{
			get
			{
				return this.GetTable<Organai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zmogus")]
	public partial class Zmogus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Vardas;
		
		private string _Pavarde;
		
		private int _Amzius;
		
		private float _Svoris;
		
		private float _Ugis;
		
		private string _KraujoGrupe;
		
		private string _Lytis;
		
		private bool _Gyvas;
		
		private bool _Narkotikai;
		
		private bool _Alkoholis;
		
		private bool _Donoras;
		
		private EntitySet<Organai> _Organais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnVardasChanging(string value);
    partial void OnVardasChanged();
    partial void OnPavardeChanging(string value);
    partial void OnPavardeChanged();
    partial void OnAmziusChanging(int value);
    partial void OnAmziusChanged();
    partial void OnSvorisChanging(float value);
    partial void OnSvorisChanged();
    partial void OnUgisChanging(float value);
    partial void OnUgisChanged();
    partial void OnKraujoGrupeChanging(string value);
    partial void OnKraujoGrupeChanged();
    partial void OnLytisChanging(string value);
    partial void OnLytisChanged();
    partial void OnGyvasChanging(bool value);
    partial void OnGyvasChanged();
    partial void OnNarkotikaiChanging(bool value);
    partial void OnNarkotikaiChanged();
    partial void OnAlkoholisChanging(bool value);
    partial void OnAlkoholisChanged();
    partial void OnDonorasChanging(bool value);
    partial void OnDonorasChanged();
    #endregion
		
		public Zmogus()
		{
			this._Organais = new EntitySet<Organai>(new Action<Organai>(this.attach_Organais), new Action<Organai>(this.detach_Organais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vardas", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Vardas
		{
			get
			{
				return this._Vardas;
			}
			set
			{
				if ((this._Vardas != value))
				{
					this.OnVardasChanging(value);
					this.SendPropertyChanging();
					this._Vardas = value;
					this.SendPropertyChanged("Vardas");
					this.OnVardasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pavarde", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Pavarde
		{
			get
			{
				return this._Pavarde;
			}
			set
			{
				if ((this._Pavarde != value))
				{
					this.OnPavardeChanging(value);
					this.SendPropertyChanging();
					this._Pavarde = value;
					this.SendPropertyChanged("Pavarde");
					this.OnPavardeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amzius", DbType="Int NOT NULL")]
		public int Amzius
		{
			get
			{
				return this._Amzius;
			}
			set
			{
				if ((this._Amzius != value))
				{
					this.OnAmziusChanging(value);
					this.SendPropertyChanging();
					this._Amzius = value;
					this.SendPropertyChanged("Amzius");
					this.OnAmziusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Svoris", DbType="Real NOT NULL")]
		public float Svoris
		{
			get
			{
				return this._Svoris;
			}
			set
			{
				if ((this._Svoris != value))
				{
					this.OnSvorisChanging(value);
					this.SendPropertyChanging();
					this._Svoris = value;
					this.SendPropertyChanged("Svoris");
					this.OnSvorisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ugis", DbType="Real NOT NULL")]
		public float Ugis
		{
			get
			{
				return this._Ugis;
			}
			set
			{
				if ((this._Ugis != value))
				{
					this.OnUgisChanging(value);
					this.SendPropertyChanging();
					this._Ugis = value;
					this.SendPropertyChanged("Ugis");
					this.OnUgisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KraujoGrupe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KraujoGrupe
		{
			get
			{
				return this._KraujoGrupe;
			}
			set
			{
				if ((this._KraujoGrupe != value))
				{
					this.OnKraujoGrupeChanging(value);
					this.SendPropertyChanging();
					this._KraujoGrupe = value;
					this.SendPropertyChanged("KraujoGrupe");
					this.OnKraujoGrupeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lytis", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Lytis
		{
			get
			{
				return this._Lytis;
			}
			set
			{
				if ((this._Lytis != value))
				{
					this.OnLytisChanging(value);
					this.SendPropertyChanging();
					this._Lytis = value;
					this.SendPropertyChanged("Lytis");
					this.OnLytisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gyvas", DbType="Bit NOT NULL")]
		public bool Gyvas
		{
			get
			{
				return this._Gyvas;
			}
			set
			{
				if ((this._Gyvas != value))
				{
					this.OnGyvasChanging(value);
					this.SendPropertyChanging();
					this._Gyvas = value;
					this.SendPropertyChanged("Gyvas");
					this.OnGyvasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Narkotikai", DbType="Bit NOT NULL")]
		public bool Narkotikai
		{
			get
			{
				return this._Narkotikai;
			}
			set
			{
				if ((this._Narkotikai != value))
				{
					this.OnNarkotikaiChanging(value);
					this.SendPropertyChanging();
					this._Narkotikai = value;
					this.SendPropertyChanged("Narkotikai");
					this.OnNarkotikaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alkoholis", DbType="Bit NOT NULL")]
		public bool Alkoholis
		{
			get
			{
				return this._Alkoholis;
			}
			set
			{
				if ((this._Alkoholis != value))
				{
					this.OnAlkoholisChanging(value);
					this.SendPropertyChanging();
					this._Alkoholis = value;
					this.SendPropertyChanged("Alkoholis");
					this.OnAlkoholisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donoras", DbType="Bit NOT NULL")]
		public bool Donoras
		{
			get
			{
				return this._Donoras;
			}
			set
			{
				if ((this._Donoras != value))
				{
					this.OnDonorasChanging(value);
					this.SendPropertyChanging();
					this._Donoras = value;
					this.SendPropertyChanged("Donoras");
					this.OnDonorasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Zmogus_Organai", Storage="_Organais", ThisKey="Id", OtherKey="ZmogausId")]
		public EntitySet<Organai> Organais
		{
			get
			{
				return this._Organais;
			}
			set
			{
				this._Organais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Organais(Organai entity)
		{
			this.SendPropertyChanging();
			entity.Zmogus = this;
		}
		
		private void detach_Organais(Organai entity)
		{
			this.SendPropertyChanging();
			entity.Zmogus = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Organai")]
	public partial class Organai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _ZmogausId;
		
		private string _Pavadinimas;
		
		private System.Nullable<float> _Svoris;
		
		private System.Nullable<decimal> _Kaina;
		
		private System.Nullable<bool> _Vidinis;
		
		private System.Nullable<bool> _Skauda;
		
		private System.Nullable<float> _Susidevėjimas;
		
		private EntityRef<Zmogus> _Zmogus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnZmogausIdChanging(int value);
    partial void OnZmogausIdChanged();
    partial void OnPavadinimasChanging(string value);
    partial void OnPavadinimasChanged();
    partial void OnSvorisChanging(System.Nullable<float> value);
    partial void OnSvorisChanged();
    partial void OnKainaChanging(System.Nullable<decimal> value);
    partial void OnKainaChanged();
    partial void OnVidinisChanging(System.Nullable<bool> value);
    partial void OnVidinisChanged();
    partial void OnSkaudaChanging(System.Nullable<bool> value);
    partial void OnSkaudaChanged();
    partial void OnSusidevėjimasChanging(System.Nullable<float> value);
    partial void OnSusidevėjimasChanged();
    #endregion
		
		public Organai()
		{
			this._Zmogus = default(EntityRef<Zmogus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZmogausId", DbType="Int NOT NULL")]
		public int ZmogausId
		{
			get
			{
				return this._ZmogausId;
			}
			set
			{
				if ((this._ZmogausId != value))
				{
					if (this._Zmogus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnZmogausIdChanging(value);
					this.SendPropertyChanging();
					this._ZmogausId = value;
					this.SendPropertyChanged("ZmogausId");
					this.OnZmogausIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pavadinimas", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Pavadinimas
		{
			get
			{
				return this._Pavadinimas;
			}
			set
			{
				if ((this._Pavadinimas != value))
				{
					this.OnPavadinimasChanging(value);
					this.SendPropertyChanging();
					this._Pavadinimas = value;
					this.SendPropertyChanged("Pavadinimas");
					this.OnPavadinimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Svoris", DbType="Real")]
		public System.Nullable<float> Svoris
		{
			get
			{
				return this._Svoris;
			}
			set
			{
				if ((this._Svoris != value))
				{
					this.OnSvorisChanging(value);
					this.SendPropertyChanging();
					this._Svoris = value;
					this.SendPropertyChanged("Svoris");
					this.OnSvorisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kaina", DbType="Money")]
		public System.Nullable<decimal> Kaina
		{
			get
			{
				return this._Kaina;
			}
			set
			{
				if ((this._Kaina != value))
				{
					this.OnKainaChanging(value);
					this.SendPropertyChanging();
					this._Kaina = value;
					this.SendPropertyChanged("Kaina");
					this.OnKainaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vidinis", DbType="Bit")]
		public System.Nullable<bool> Vidinis
		{
			get
			{
				return this._Vidinis;
			}
			set
			{
				if ((this._Vidinis != value))
				{
					this.OnVidinisChanging(value);
					this.SendPropertyChanging();
					this._Vidinis = value;
					this.SendPropertyChanged("Vidinis");
					this.OnVidinisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skauda", DbType="Bit")]
		public System.Nullable<bool> Skauda
		{
			get
			{
				return this._Skauda;
			}
			set
			{
				if ((this._Skauda != value))
				{
					this.OnSkaudaChanging(value);
					this.SendPropertyChanging();
					this._Skauda = value;
					this.SendPropertyChanged("Skauda");
					this.OnSkaudaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Susidevėjimas", DbType="Real")]
		public System.Nullable<float> Susidevėjimas
		{
			get
			{
				return this._Susidevėjimas;
			}
			set
			{
				if ((this._Susidevėjimas != value))
				{
					this.OnSusidevėjimasChanging(value);
					this.SendPropertyChanging();
					this._Susidevėjimas = value;
					this.SendPropertyChanged("Susidevėjimas");
					this.OnSusidevėjimasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Zmogus_Organai", Storage="_Zmogus", ThisKey="ZmogausId", OtherKey="Id", IsForeignKey=true)]
		public Zmogus Zmogus
		{
			get
			{
				return this._Zmogus.Entity;
			}
			set
			{
				Zmogus previousValue = this._Zmogus.Entity;
				if (((previousValue != value) 
							|| (this._Zmogus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Zmogus.Entity = null;
						previousValue.Organais.Remove(this);
					}
					this._Zmogus.Entity = value;
					if ((value != null))
					{
						value.Organais.Add(this);
						this._ZmogausId = value.Id;
					}
					else
					{
						this._ZmogausId = default(int);
					}
					this.SendPropertyChanged("Zmogus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
